### ISSUE TITLE
Supporting buffer suballocation

### ISSUE THREAD

**Issue by martty** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#88] opened 2019-11-19 07:24 UTC
Are there plans to support buffer suballocation? 

It is highly beneficial to suballocate the buffers that are returned by VMA, and VMA already has facilities for suballocating - just not buffers. In the current case I would have to either implement / reimplement the same allocators on top of the VMA-returned buffers or go with a fully custom solution to handle suballocation.

**Comment by adam-sawicki-a** [comment] 2019-11-19 11:25
Thank you for this suggestion. Suballocation of parts of a single buffer is a higher-level feature that can be implemented on top of VMA, but I agree it would be nice to support it. I have it on my TODO list for the future, so it might be added to the library, I just don't know when. In the meantime, please feel free to propose the API for this feature you would like to see.

**Comment by kennyalive** [comment] 2019-11-20 17:04
I'd like to add a comment how we use VMA at work to do buffer suballocation. Buffer suballocation is the feature of our engine and our custom memory allocation subsystem supports this. When I started to integrate VMA I had to find a way to implement this since engine interfaces expect you can do this. Here's the hack:
- We use VmaPools to manage top-level large allocations.
- When VmaPool is used to back a large buffer (to suballocate regions from) I specify callback (which probably should be used only to gather stats or similar innocent things) and that callbacks allows me to get VkDeviceMemory associated with VmaPool's allocation... :imp:
- Then we create large buffer to suballocate from and bind it to VkDeviceMemory associated with VmaPool. Buffer creation and memory binding should be done using regular vulkan code without VMA. Otherwise VMA will mark entire VmaPool as occupied by buffer and won't allow to suballocate.
- At this point you can VMA to allocate memory since VMA assumes that entire VmaPool is unallocated. Of course this approach has limitation (we have to use memory level functionality like vmaAllocateMemory and it get offsets in large buffer and vmaCreateBuffer would not work here) but it's better than no VMA at all. For example we have full benefits of VmaDumpVis tool functionality. And of course for other allocation types like regular small buffers or images we use VMA as designed.
- And yes, it would be nice to have this a part of the API.

**Comment by adam-sawicki-a** [comment] 2019-11-21 09:29
Wow, that's an interesting solution. Thanks for sharing it. I will consider adding feature of buffer suballocation to the library.

How do you handle the problem of barriers and synchronization in case you suballocate parts of one big buffer if you want to use one part let's say for reading on the GPU as uniform or vertex buffer while writing to other part e.g. as copy destination, on a transfer queue?

**Comment by kennyalive** [comment] 2019-11-21 09:43
I did not work with that part of functionality but looking at the code it looks like this directly supported by the vulkan API and VkBufferMemoryBarrier allows to specify buffer's subregion and we use that feature to perform ownership transition of the required part of the buffer.

**Comment by helixd-2k18** [comment] 2021-03-18 12:36
In my projects now, this would obviously come in handy…
Considering there all sorts of realities of device address and descriptors.

**Comment by Vincent-P** [comment] 2021-04-26 19:19
I'm not sure how the API for suballocations should look like but maybe we can infer it from its use cases.

I can think of 2 different use cases that most renderer would need:

- An dynamic uniform ring buffer. If we assume that the entire buffer will be used for uniforms I guess there is no need for complex synchronization and barriers? An offset would probably be enough to feed into `vkCmdBindDescriptorSets`. The only part that could be hard is figuring out overruns to avoid writing into sub-allocations currently used by the GPU.
- Big storage pools. For example if I want to have one big vertex buffer accessible in a bindless fashion, I'd like to "allocate" N vertices when loading a mesh and maybe "free" those vertices if the mesh isn't used anymore. This would probably need to return at least an offset and a size for buffer memory barriers.

As for queue ownership transfers, I'm not sure if it is possible to use different offsets of the same buffer in different queues?
If that's not the case it would be easier to just assume the higher-level code is taking care of it: first transfer the whole buffer to the copy queue, transfer it back to the graphics/compute queue to read it.

**Comment by devshgraphicsprogramming** [comment] 2021-04-26 19:23
> Big storage pools. For example if I want to have one big vertex buffer accessible in a bindless fashion, I'd like to "allocate" N vertices when loading a mesh and maybe "free" those vertices if the mesh isn't used anymore. This would probably need to return at least an offset and a size for buffer memory barriers.

I think this is the original reason I subscribed to the issue.

Actually it needs to do a bit more than just return an offset aand size, it should take into account alignment requested.

> As for queue ownership transfers, I'm not sure if it is possible to use different offsets of the same buffer in different queues?

Same queue family yes, otherwise:
with concurrent usage flag on the buffer itself, yes, without its UB.

**Comment by adam-sawicki-a** [comment] 2021-04-27 08:42
I agree that any synchronization (barriers, queue type ownership transfer) should be a responsibility of the user.

As for the API, I plan to implement something similar to what I've already done in D3D12 Memory Allocator as "virtual allocator" functionality: https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/blob/master/src/D3D12MemAlloc.h#L436

**Comment by Vincent-P** [comment] 2021-04-30 15:44
It looks great! Do you have any ideas on when it's going to be available?

**Comment by adam-sawicki-a** [comment] 2021-10-30 21:41
I finished everything I planned for the implementation of this feature, as well as tests and documentation, and merged it to the main branch.

Please feel free to post any additional comments about this feature.

**Closed by adam-sawicki-a** 2021-10-30 21:41 UTC
Labels: enhancement, next release

**Comment by null77** [comment] 2021-11-01 13:30
Big thanks! We haven't tested yet, I'll update this issue if we have any additional comments.

**Comment by kvark** [comment] 2022-04-16 00:23
@adam-sawicki-a I'd like to give it a try. Could you provide any pointers on where this functionality lives, and how to use it?

**Comment by adam-sawicki-a** [comment] 2022-04-19 08:30
It is called "virtual allocator", described in documentation here:
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/virtual_allocator.html

**Comment by adam-sawicki-a** [comment] 2023-01-31 16:28
I started implementing buffer suballocation feature - see branch "feature-buffer-suballocation" and issue #258 for details.
