### ISSUE TITLE
[FR] Consider switching to unix LF

### ISSUE THREAD

**Issue by werdahias** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#366] opened 2023-09-07 16:05 UTC
Currently the header is using DOS / windows LF. As the unix LF is more common I suggest to switch to it.

**Comment by adam-sawicki-a** [comment] 2023-09-07 17:43
This is a duplicate of #272. This problem keeps coming back after merging pull requests from contributors whose text editors convert line endings automatically and don't respect ".editorconfig" file, which we have in this project and which configures `end_of_line = lf`. I don't think this is a problem though, as modern text editors support various line ending modes.

**Closed by adam-sawicki-a** 2023-09-07 17:43 UTC

**Comment by turol** [comment] 2023-09-08 10:13
You could set up a CI action which fails any PR which breaks the line endings.
