### ISSUE TITLE
Change ifdef guard for VMA_USE_STL_SHARED_MUTEX to use __cplusplus version?

### ISSUE THREAD

**Issue by jamesRumbleh** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#52] opened 2018-12-21 11:19 UTC
Hi,

Could the following ifdef guard for determining whether to use std::shared_mutex i.e. features of c++17 be determined using something more generic like "#if __cplusplus >= 201403L"?

"
// Minimum Visual Studio 2015 Update 2
#if defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 190023918
    #define VMA_USE_STL_SHARED_MUTEX 1
#endif
"

I can see two problems this causes:
- Support for VMA_USE_STL_SHARED_MUTEX is currently limited to MSC only.
- We're using Visual Studio 2017 supporting up to c++14 but with the current ifdef guard (shown above) we're getting VMA_USE_STL_SHARED_MUTEX defined and then attempting and failing to use std::shared_mutex.

With VS 2017 and c++14 if I switch to use #if __cplusplus >= 201403L we do not get VMA_USE_STL_SHARED_MUTEX defined and fallback to using VmaRWMutex appropriately.

We're currently using Version 2.1 and can't move to Version 2.2 due to the above.

FYI I'm one of the developers working on the PowerVR SDK and we've been using VMA since Version 2.0.0-alpha.4 - we love it.

**Comment by adam-sawicki-amd** [comment] 2018-12-21 12:31
Hi,

First of all, thank you for using and appreciation of VMA. I'm glad to see that despite it is being developed mostly on PC Windows, it is useful also in Vulkan programming for other kinds of GPUs.

This problem shouldn't stop you from upgrading the library. Please note that every such configuration macro is handled like this: `#ifndef MACRO #if CONDITION #define MACRO #endif #endif`, so that you can override the logic inside even without modifying the source of VMA, by just defining this macro before include:

```cpp
#define VMA_USE_STL_SHARED_MUTEX 0
#include "vk_mem_alloc.h"
```

But I agree with you - usage of `shared_mutex` should be enabled for any C++17 conforming compiler. There is one caveat though: Visual Studio doesn't define `__cplusplus` macro properly by default, so it has to be handled in other way.

I've submitted my proposed solution to "master" branch. Can you please check if it solves the problem for you?

**Comment by adam-sawicki-amd** [comment] 2018-12-28 16:52
I assume the issue is fixed now and I close the ticket. Please let me know if you find any problems with it.

**Closed by adam-sawicki-amd** 2018-12-28 16:52 UTC

**Comment by jamesRumbleh** [comment] 2019-01-02 08:08
Yeah we definitely get good use out of VMA so thanks for the great library! Aha yeah of course we'll do as you suggest and disable STL_SHARED_MUTEX for now. Thanks for the fix in master. It looks fine to me.
