### ISSUE TITLE
Dealing with overcommitted VRAM

### ISSUE THREAD

**Issue by JustSid** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#81] opened 2019-10-25 23:08 UTC
First of all, I just wanted to say thanks for VMA, it's a fantastic library! We are using VMA in the Vulkan version of our engine that powers [X-Plane](https://www.x-plane.com/), which we are hoping to ship later this year.

Our big problem is dealing with overcommitted VRAM. One of the things that makes X-Plane interesting is that users and third parties can author a wide variety of different scenery and autogen, making it trivial for a user to load up plugins and hit against the VRAM limit. Our goal is to deal with this gracefully, so we have a dynamic paging engine that can automatically down-scales textures if the memory pressure becomes too great, and also can defer allocations if we are running out of VRAM. We also use our own memory pools and limit the amount of memory VMA can allocate based on what the Vulkan device reports it can do through `VK_EXT_memory_budget`.

The problem however arises because of allocations that VMA is unaware of, and that don't count against VMAs own limits. On Nvidia and AMD, pipeline and descriptor memory counts against the budget from what we can tell, and there also seem to be other opaque things like swapchain images. I can get X-Plane into a state where we start out just fine, but loading in more scenery later on will cause this opaque memory to grow in size and suddenly we'll find ourselves in a situation where we have too much VRAM being used and performance will crawl to a halt (or the application will just outright crash).

Our paging engine can't solve this problem by itself, because as it stands, VMA doesn't give us any good access to say "hey, we want to get rid of this Vulkan device memory allocation, please mark it as unusable for future allocations and we'll get rid of everything currently in it". Not to mention that associating an allocation with a VMA block isn't straightforward either without relying on under the hood things. A custom defragmenter might be able to do the job, but we aren't just looking at moving the memory around but also compacting it (ie going back to disk and reloading the image with a lower mip for example). This seems like heavily absuing the system, and the `VmaBlockMetadata` class also lacks a good way to lock everything down to avoid allocations happening while we are busy getting the new image data ready.

And now I'm here. I'm wondering if maybe there was something that I've overlooked that would easily solve our problem. Or if not, I was wondering if there might already be a grand vision for solving a problem like this. I'm happy to volunteer time to implement this and/or help out with an interface for this. Ideally we'd like to have a general solution upstream than having a private fork with changes just for us.

**Comment by JustSid** [comment] 2019-11-06 16:17
I finally got around to checking the branch out, and I love the additions, but there is one missing feature imho. And that is, what happens when the budget suddenly gets tighter than it used to be? Say for example you load some more pipelines, or have a new swapchain or a new descriptor pool or whatever. You can find yourself in a situation where you suddenly are over budget without allocating new VRAM directly. In this situation it’s super hard to get VMA to evict all allocations from a single device memory block so it can be freed back to the system. 

And that is exactly what I'm trying to achieve. I love that I no longer have to track the budget higher up and can instead rely on VMA to just fail the allocation, but ideally I'd want a way to actively free memory back to the system. Of course this can't be achieved by VMA dumping the whole thing, it'd be a lifetime tracking nightmare. And also needs support by the application, which needs to do things such as resizing textures to make them fit into a smaller footprint.  I guess the best way right now is to have a custom defragmentation routine that can compact the allocations and also resize them in such a way that by the end you are left with less device heap allocations than before.

**Comment by adam-sawicki-a** [comment] 2019-11-06 17:55
My current plan is to add following features before budget management is finished and merged to master:
- Normally the library leaves one empty block so it doesn't allocate/deallocate whole block when user repetedly allocates/frees one small buffer, but when we are over budget, that empty block will be freed.
- There will be a function added that would try to free some allocations to make some more blocks empty and release them when over budget, but that can be done only to allocations that "can become lost".

What do you think about it?

I'm afraid there is not much more that can be done in this regard until the library gets better defragmentation feature.

**Comment by JustSid** [comment] 2019-11-06 19:51
I like the idea of both of these changes a lot, especially the first one, since it'd be a free "win" of ~256mb.

May I ask if you have plans for better defragmentation features? I could imagine a host application guided defragmentation scheme could work well here, to fill in the missing pieces for image allocations. Not sure how it is for other engines, but in our case it's actually quite trivial to re-create the `VkImageCreateInfo` structure necessary to move a tiling optimal image. The host application could also provide information such as image layouts, so VMA could do the necessary transitions. Eg. transfer src optimal instead of requiring a bulk transition of all potentially eligible images to the general layout, but then not necessarily moving all images due to the constraints passed in to the algorithm.

**Comment by adam-sawicki-a** [comment] 2019-11-07 09:27
There is a plan to implement new defragmentation, but that requires major library redesign, so it won't happen any time soon. The problem is that VMA doesn't remember `VkImage` associated with an allocation to be able to issue `vkCmdCopyImage`, not to mention `VkImageCreateInfo` structure needed to be able to recreate it. Current plan is to just return a list of recommended moves (like source block and offset + destination block and offset), while the user has to recreate his resources and make the copies. Any feedback is welcomed.

**Comment by JustSid** [comment] 2019-11-07 16:29
That’s kinda what I was thinking as well with my host application guided defragmentation idea. It’s not necessary for VMA to track all that info (imho), since I reckon most engines have enough information to recreate most of it. At least in our case it’s trivial to recreate the image and buffer create infos, and of course we know whether it’s an image or buffer. 

So I think hoisting that responsibility up into the host application is perfectly fine.

**Comment by adam-sawicki-a** [comment] 2019-11-18 14:05
I've merged budget management to master branch. Please let me know if it works for you.

**Closed** 2019-11-22 13:42 UTC
