### ISSUE TITLE
feature request : support "virtual buffer"

### ISSUE THREAD

**Issue by zhaijialong** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#134] opened 2020-06-04 04:34 UTC
"virtual buffer" : [https://developer.nvidia.com/vulkan-memory-management](https://developer.nvidia.com/vulkan-memory-management)

I know we can build a "virtual buffer" allocator on top of vma/d3d12ma (that is what we did), but if that can be a built-in feature it would be better for consistent usage.

Especially I think the "virtual buffer" is very useful for d3d12，because it doesn't need 64KB alignment.

**Comment by zhaijialong** [comment] 2020-06-04 04:47
just noticed there is a redundant issue #88 ，so feel free to close this issue if you want :)

**Comment by adam-sawicki-a** [comment] 2020-06-04 08:37
That's right. Exposing allocation algorithms alone without really allocating GPU memory, to be useful for e.g. sub-allocation inside a single buffer, is on the TODO list, and it's a duplicate of #88. I will put it higher :)

**Closed by adam-sawicki-a** 2020-06-04 08:37 UTC
Labels: duplicate
